[env]
VER="0"

[build]
cmd = """
arduino-cli compile --fqbn esp32:esp32:esp32 . && \
arduino-cli upload -p /dev/ttyUSB$VER --fqbn esp32:esp32:esp32 .
"""

[custom.mon]
cmd="arduino-cli monitor -p /dev/ttyUSB0 -c baudrate=115200"
run = false
